---

- name: Copy system users deploy keys
  become_user: "{{ user }}"
  copy: src="{{ item.src }}" dest="{{ item.path }}"
  with_items: "{{ authorization.key_files | default({}) }}"
  tags:
    - system_users
    - public_keys
    - deployment_keys

- name: Correct SSH Deploy key permissions
  become_user: "{{ user }}"
  file: path={{ item.path }} state={{ item.state }}
        owner={{ item.owner }}
        mode=0600
  with_items: "{{ authorization.key_files | default({}) }}"
  tags:
    - system_users
    - public_keys
    - deployment_keys
